name: Build and Test Campus and Enrollment React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x,15.x,16.x,17.x,18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
    - name: npm ci, build, seed 
      run: |
        npm ci
        npm run seed
        npm run start