name: Build and Test Campus and Enrollment React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: npm i, seed
        run: |
          npm i
          npm run seed

  redeploy_on_render:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger front-end redeploy and seed
        run: |
          curl -X GET \
          https://api.render.com/deploy/srv-cnlajof79t8c73al6vs0?key=M87oPrECWwk
