name: Build and Test Campus and Enrollment React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
    - name: npm ci, build, seed 
      run: |
        npm ci
        npm run seed
        npm run start