name: Build and Test Campus and Enrollment React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: npm i, seed
        run: |
          npm i
          npm run seed
